# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=20000)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
