# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'images/%Y/%m/%d')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
