# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160110_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
