# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160110_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='main.Blog'),
            preserve_default=False,
        ),
    ]
