# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='respectiveblog',
            field=models.ForeignKey(default='main', on_delete=django.db.models.deletion.CASCADE, to='main.Blog'),
            preserve_default=False,
        ),
    ]
